#!/bin/bash

usage () {
	echo "Usage: $0 <containers|images|all>"
	echo "  containers - removes stopped docker containers"
	echo "  images     - removes unnamed docker images"
	echo "  all        - all of the above"
	echo "  help       - prints this message"
}

remove_containers () {
	CONTAINERS=$(docker ps -a|awk '/Exited /{printf("%s ", $1)}')
	if [[ -z $CONTAINERS ]]  ; then
		echo "no inactive containers found"
	else
		docker rm $CONTAINERS
	fi
}

remove_images () {
	IMAGES=$(docker images | grep none | awk '{print $3}' | sort -r)
	if [[ -z $IMAGES ]]  ; then
		echo "no unused images found"
	else
		docker rmi $IMAGES
	fi
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

case $1 in
	containers)
		remove_containers
		;;
	images)
		remove_images
		;;
	all)
		remove_containers
		remove_images
		;;
	help)
		usage
		;;
esac
